name: Run Sample Test

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 10 PM EST (2 AM UTC)
  workflow_dispatch: # Allows manual triggering of the workflow with inputs
    inputs:
      testng_file:
        description: 'Select TestNG XML file to execute'
        required: false
        options:
          - 'testng.xml'          
        type: choice 

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:    

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
            version: 1.10.1
            args: -limit 10
            browsers: chrome
            last-versions: 1

      - name: Run TestNG XML file
        if: inputs.testng_file != null
        run: mvn clean test -DtestType=${{ inputs.testng_file }}

      - name: Archive report
        uses: actions/upload-artifact@v2
        with:
          name: extent-report
          path: reports/automationreport.html
