name: Run Sample Test

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 10 PM EST (2 AM UTC)
  workflow_dispatch: # Allows manual triggering of the workflow with inputs
    inputs:
      testng_file:
        description: 'Select TestNG XML file to execute'
        required: false
        options:
          - 'testng.xml'          
        type: choice 

jobs:
  run_tests:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ steps.run_tests.outputs.job_status }}

    steps:    

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Cache Selenoid binary
        uses: actions/cache@v2
        with:
          path: ~/.aerokube/selenoid
          key: ${{ runner.os }}-selenoid
          restore-keys: ${{ runner.os }}-selenoid
          
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
            version: 1.10.1
            args: -limit 10
            browsers: chrome
            last-versions: 1

      - name: Run TestNG XML file
        if: inputs.testng_file != null
        id: run_tests
        run: |
          mvn clean test -DtestType=${{ inputs.testng_file }}
          test_exit_code=$?
          echo "Test exit code: $test_exit_code"
          if [ $test_exit_code -ne 0 ]; then
            echo "Tests failed"
            echo "::set-output name=job_status::failure"
            exit $test_exit_code
          else
            echo "Tests passed"
            echo "::set-output name=job_status::success"
          fi
        continue-on-error: true

      - name: Debug job status
        run: |
          echo "Job status: ${{ steps.run_tests.outputs.job_status }}"
        if: always()

      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: extent-report
          path: reports/automationreport.html
